service: goldgate

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-2

functions:
  licenses:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get